import Foundation
@testable import MeetingTranscriber

/// Mock protocol generator that captures the transcript instead of calling Claude CLI.
class MockProtocolGen: ProtocolGenerating {
    var generateCalled = false
    var capturedTranscript: String?
    var capturedTitle: String?
    // swiftlint:disable:next discouraged_optional_boolean
    var capturedDiarized: Bool?
    var capturedMeetingStartTime: Date?
    var capturedScheduled: ProtocolGenerator.ScheduledMeetingContext?
    var shouldThrow = false

    func generate(
        transcript: String,
        title: String,
        diarized: Bool,
        meetingStartTime: Date?,
        scheduled: ProtocolGenerator.ScheduledMeetingContext?,
    ) throws -> String {
        generateCalled = true
        capturedTranscript = transcript
        capturedTitle = title
        capturedDiarized = diarized
        capturedMeetingStartTime = meetingStartTime
        capturedScheduled = scheduled
        if shouldThrow {
            throw NSError(
                domain: "MockProtocolGen",
                code: 1,
                userInfo: [NSLocalizedDescriptionKey: "Mock protocol error"],
            )
        }
        return """
        # Meeting Protocol - \(title)
        **Date:** 2026-03-06

        ---

        ## Summary
        Test protocol generated by mock.
        """
    }
}

/// Test-only convenience for generators whose meeting time is irrelevant to a test.
extension ProtocolGenerating {
    func generate(transcript: String, title: String, diarized: Bool) async throws -> String {
        try await generate(transcript: transcript, title: title, diarized: diarized, meetingStartTime: nil, scheduled: nil)
    }
}
